ctit085
/home/s2240084/conFEDential/venv/bin/python
absl-py==2.1.0
aiohttp==3.9.3
aiosignal==1.3.1
appdirs==1.4.4
asttokens==2.4.1
astunparse==1.6.3
async-timeout==4.0.3
attrs==23.2.0
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
comm==0.2.2
contourpy==1.2.0
cryptography==41.0.7
cycler==0.12.1
datasets==2.18.0
decorator==5.1.1
dill==0.3.8
docker-pycreds==0.4.0
exceptiongroup==1.2.0
executing==2.0.1
FedArtML==0.1.32
filelock==3.13.1
flatbuffers==24.3.7
flwr==1.7.0
fonttools==4.50.0
frozenlist==1.4.1
fsspec==2024.2.0
gast==0.5.4
gitdb==4.0.11
GitPython==3.1.42
google-pasta==0.2.0
grpcio==1.62.1
h5py==3.10.0
huggingface-hub==0.22.0
idna==3.6
ipython==8.22.2
ipywidgets==8.1.2
iterators==0.0.2
jedi==0.19.1
Jinja2==3.1.3
joblib==1.3.2
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyterlab_widgets==3.0.10
keras==3.1.1
kiwisolver==1.4.5
libclang==18.1.1
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.3
matplotlib-inline==0.1.6
mdurl==0.1.2
ml-dtypes==0.3.2
mpmath==1.2.1
msgpack==1.0.8
multidict==6.0.5
multiprocess==0.70.16
namex==0.0.7
networkx==3.2.1
npzviewer==0.2.0
numpy==1.26.4
nvidia-cublas-cu11==11.11.3.6
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu11==11.8.87
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu11==11.8.89
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu11==11.8.89
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu11==8.7.0.84
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu11==10.9.0.58
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu11==10.3.0.86
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu11==11.4.1.48
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu11==11.7.5.86
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu11==2.20.5
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu11==11.8.86
nvidia-nvtx-cu12==12.1.105
opt-einsum==3.3.0
optree==0.10.0
packaging==24.0
pandas==1.5.3
parso==0.8.3
pexpect==4.9.0
pillow==10.2.0
prompt-toolkit==3.0.43
protobuf==4.25.3
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==15.0.2
pyarrow-hotfix==0.6
pycparser==2.21
pycryptodome==3.20.0
pydantic==1.10.14
Pygments==2.17.2
pyparsing==3.1.2
PyQt5==5.15.10
PyQt5-Qt5==5.15.2
PyQt5-sip==12.13.0
python-dateutil==2.9.0.post0
pytorch-triton==3.0.0+989adb9a29
pytz==2024.1
PyYAML==6.0.1
ray==2.6.3
referencing==0.34.0
requests==2.31.0
rich==13.7.1
rpds-py==0.18.0
scikit-learn==1.4.1.post1
scipy==1.12.0
sentry-sdk==1.43.0
setproctitle==1.3.3
six==1.16.0
smmap==5.0.1
stack-data==0.6.3
sympy==1.12
tensorboard==2.16.2
tensorboard-data-server==0.7.2
tensorflow==2.16.1
tensorflow-io-gcs-filesystem==0.36.0
termcolor==2.4.0
threadpoolctl==3.4.0
torch==2.4.0.dev20240330+cu118
tqdm==4.66.2
traitlets==5.14.2
triton==2.2.0
typing_extensions==4.8.0
tzdata==2024.1
urllib3==2.2.1
wandb==0.16.5
wcwidth==0.2.13
Werkzeug==3.0.1
widgetsnbextension==4.0.10
wrapt==1.16.0
xxhash==3.4.1
yarl==1.9.4
srun: Warning: can't run 1 processes on 2 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 2 nodes, setting nnodes to 1
2024-03-30 17:48:47.536967: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-30 17:48:49.798738: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-30 17:48:53.446567: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-30 17:48:53.869212: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-03-30 17:48:54.813104: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-30 17:48:59.667364: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: Network error (ConnectTimeout), entering retry loop.
wandb: Network error (ConnectTimeout), entering retry loop.
Loaded 168 configs, running...
Traceback (most recent call last):
  File "/home/s2240084/conFEDential/src/batch_run_simulation.py", line 66, in <module>
    main()
  File "/home/s2240084/conFEDential/src/batch_run_simulation.py", line 62, in main
    run_simulation(config, client_resources, batch_run_name)
  File "/home/s2240084/conFEDential/src/run_simulation.py", line 129, in run_simulation
    train_loaders, test_loader = utils.load_data_loaders_from_config(config)
  File "/home/s2240084/conFEDential/src/utils/data.py", line 23, in load_data_loaders_from_config
    return dataclass.load_data(client_count, batch_size, preprocess_fn, alpha, percent_non_iid)
  File "/home/s2240084/conFEDential/src/federated_datasets/MNIST.py", line 35, in load_data
    train_dataset, test_dataset = load_dataset("mnist", cache_dir="cache/mnist", split=["train", "test"])
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 2556, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 2228, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 1879, in dataset_module_factory
    raise e1 from None
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 1812, in dataset_module_factory
    raise ConnectionError(f"Couldn't reach '{path}' on the Hub ({type(e).__name__})")
ConnectionError: Couldn't reach 'mnist' on the Hub (ConnectTimeout)
Traceback (most recent call last):
  File "/home/s2240084/conFEDential/src/batch_run_simulation.py", line 66, in <module>
    main()
  File "/home/s2240084/conFEDential/src/batch_run_simulation.py", line 62, in main
    run_simulation(config, client_resources, batch_run_name)
  File "/home/s2240084/conFEDential/src/run_simulation.py", line 129, in run_simulation
    train_loaders, test_loader = utils.load_data_loaders_from_config(config)
  File "/home/s2240084/conFEDential/src/utils/data.py", line 23, in load_data_loaders_from_config
    return dataclass.load_data(client_count, batch_size, preprocess_fn, alpha, percent_non_iid)
  File "/home/s2240084/conFEDential/src/federated_datasets/MNIST.py", line 35, in load_data
    train_dataset, test_dataset = load_dataset("mnist", cache_dir="cache/mnist", split=["train", "test"])
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 2556, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 2228, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 1879, in dataset_module_factory
    raise e1 from None
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 1812, in dataset_module_factory
    raise ConnectionError(f"Couldn't reach '{path}' on the Hub ({type(e).__name__})")
ConnectionError: Couldn't reach 'mnist' on the Hub (ConnectTimeout)
srun: error: ctit085: task 0: Exited with exit code 1
Loaded 168 configs, running...
Traceback (most recent call last):
  File "/home/s2240084/conFEDential/src/batch_run_simulation.py", line 66, in <module>
    main()
  File "/home/s2240084/conFEDential/src/batch_run_simulation.py", line 62, in main
    run_simulation(config, client_resources, batch_run_name)
  File "/home/s2240084/conFEDential/src/run_simulation.py", line 129, in run_simulation
    train_loaders, test_loader = utils.load_data_loaders_from_config(config)
  File "/home/s2240084/conFEDential/src/utils/data.py", line 23, in load_data_loaders_from_config
    return dataclass.load_data(client_count, batch_size, preprocess_fn, alpha, percent_non_iid)
  File "/home/s2240084/conFEDential/src/federated_datasets/MNIST.py", line 35, in load_data
    train_dataset, test_dataset = load_dataset("mnist", cache_dir="cache/mnist", split=["train", "test"])
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 2556, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 2228, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 1879, in dataset_module_factory
    raise e1 from None
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 1812, in dataset_module_factory
    raise ConnectionError(f"Couldn't reach '{path}' on the Hub ({type(e).__name__})")
ConnectionError: Couldn't reach 'mnist' on the Hub (ConnectTimeout)
Traceback (most recent call last):
  File "/home/s2240084/conFEDential/src/batch_run_simulation.py", line 66, in <module>
    main()
  File "/home/s2240084/conFEDential/src/batch_run_simulation.py", line 62, in main
    run_simulation(config, client_resources, batch_run_name)
  File "/home/s2240084/conFEDential/src/run_simulation.py", line 129, in run_simulation
    train_loaders, test_loader = utils.load_data_loaders_from_config(config)
  File "/home/s2240084/conFEDential/src/utils/data.py", line 23, in load_data_loaders_from_config
    return dataclass.load_data(client_count, batch_size, preprocess_fn, alpha, percent_non_iid)
  File "/home/s2240084/conFEDential/src/federated_datasets/MNIST.py", line 35, in load_data
    train_dataset, test_dataset = load_dataset("mnist", cache_dir="cache/mnist", split=["train", "test"])
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 2556, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 2228, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 1879, in dataset_module_factory
    raise e1 from None
  File "/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/datasets/load.py", line 1812, in dataset_module_factory
    raise ConnectionError(f"Couldn't reach '{path}' on the Hub ({type(e).__name__})")
ConnectionError: Couldn't reach 'mnist' on the Hub (ConnectTimeout)
srun: error: ctit086: task 0: Exited with exit code 1
