ctit088
2024-07-01 01:55:18,513	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=32 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,accelerator_type:G,1,CPU,32,memory,150123589428,object_store_memory,68624395468 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --redis-address=None --temp-dir=/tmp/ray --metrics-agent-port=59027 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --temp-dir=/tmp/ray --webui= RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:52383 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs -Dray.session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --log_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --resource_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --metrics-agent-port=59027 --metrics_export_port=53174 --object_store_memory=68624395468 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --labels= --head --num_prestart_python_workers=32 "--agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=53174 --dashboard-agent-port=59027 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --runtime-env-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --log-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-30_20-02-14_305409_1614546 --gcs-address=10.20.240.18:52383 --minimal"` due to (pid=1614755, name='raylet')
2024-07-01 01:55:18,514	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=2 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,CPU,2,memory,164658337997,object_store_memory,74853573427 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --redis-address=None --metrics-agent-port=46078 --runtime-env-agent-port=58341 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --temp-dir=/tmp/ray --webui= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:47294 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs -Dray.session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --resource_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --metrics-agent-port=46078 --metrics_export_port=61221 --runtime_env_agent_port=58341 --object_store_memory=74853573427 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --labels= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 --head --num_prestart_python_workers=2 "--dashboard_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=61221 --dashboard-agent-port=46078 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-28_07-48-43_813905_1894806 --gcs-address=10.20.240.18:47294 --minimal" "--runtime_env_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=10.20.240.18 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --runtime-env-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --temp-dir=/tmp/ray"` due to (pid=1894993, name='raylet')
2024-07-01 01:55:18,623	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/autoscaler/_private/monitor.py --logs-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:52383 --monitor-ip=10.20.240.18` due to (pid=1614715, name='python3')
2024-07-01 01:55:18,623	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/log_monitor.py --logs-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --gcs-address=10.20.240.18:52383 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5` due to (pid=1614784, name='python3')
2024-07-01 01:55:18,623	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/autoscaler/_private/monitor.py --logs-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:47294 --monitor-ip=10.20.240.18` due to (pid=1894943, name='python3')
2024-07-01 01:55:18,623	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/log_monitor.py --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --logs-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --gcs-address=10.20.240.18:47294 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5` due to (pid=1895026, name='python3')
2024-07-01 01:55:18,633	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=32 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,accelerator_type:G,1,CPU,32,memory,150123589428,object_store_memory,68624395468 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --redis-address=None --temp-dir=/tmp/ray --metrics-agent-port=59027 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --temp-dir=/tmp/ray --webui= RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:52383 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs -Dray.session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --log_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --resource_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --metrics-agent-port=59027 --metrics_export_port=53174 --object_store_memory=68624395468 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --labels= --head --num_prestart_python_workers=32 "--agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=53174 --dashboard-agent-port=59027 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --runtime-env-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --log-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-30_20-02-14_305409_1614546 --gcs-address=10.20.240.18:52383 --minimal"` due to (pid=1614755, name='raylet')
2024-07-01 01:55:18,634	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=2 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,CPU,2,memory,164658337997,object_store_memory,74853573427 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --redis-address=None --metrics-agent-port=46078 --runtime-env-agent-port=58341 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --temp-dir=/tmp/ray --webui= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:47294 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs -Dray.session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --resource_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --metrics-agent-port=46078 --metrics_export_port=61221 --runtime_env_agent_port=58341 --object_store_memory=74853573427 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --labels= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 --head --num_prestart_python_workers=2 "--dashboard_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=61221 --dashboard-agent-port=46078 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-28_07-48-43_813905_1894806 --gcs-address=10.20.240.18:47294 --minimal" "--runtime_env_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=10.20.240.18 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --runtime-env-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --temp-dir=/tmp/ray"` due to (pid=1894993, name='raylet')
2024-07-01 01:55:18,639	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=32 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,accelerator_type:G,1,CPU,32,memory,150123589428,object_store_memory,68624395468 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --redis-address=None --temp-dir=/tmp/ray --metrics-agent-port=59027 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --temp-dir=/tmp/ray --webui= RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:52383 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs -Dray.session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --log_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --resource_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --metrics-agent-port=59027 --metrics_export_port=53174 --object_store_memory=68624395468 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --labels= --head --num_prestart_python_workers=32 "--agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=53174 --dashboard-agent-port=59027 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --runtime-env-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --log-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-30_20-02-14_305409_1614546 --gcs-address=10.20.240.18:52383 --minimal"` due to (pid=1614755, name='raylet')
2024-07-01 01:55:18,640	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=2 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,CPU,2,memory,164658337997,object_store_memory,74853573427 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --redis-address=None --metrics-agent-port=46078 --runtime-env-agent-port=58341 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --temp-dir=/tmp/ray --webui= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:47294 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs -Dray.session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --resource_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --metrics-agent-port=46078 --metrics_export_port=61221 --runtime_env_agent_port=58341 --object_store_memory=74853573427 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --labels= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 --head --num_prestart_python_workers=2 "--dashboard_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=61221 --dashboard-agent-port=46078 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-28_07-48-43_813905_1894806 --gcs-address=10.20.240.18:47294 --minimal" "--runtime_env_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=10.20.240.18 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --runtime-env-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --temp-dir=/tmp/ray"` due to (pid=1894993, name='raylet')
2024-07-01 01:55:18,641	ERR scripts.py:1127 -- Could not terminate `ray::ClientAppActor "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""` due to (pid=1615491, name='ray::ClientAppActor')
2024-07-01 01:55:18,641	ERR scripts.py:1127 -- Could not terminate `ray::ClientAppActor.run "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""` due to (pid=1615492, name='ray::ClientAppActor.run')
2024-07-01 01:55:18,642	ERR scripts.py:1127 -- Could not terminate `ray::ClientAppActor.run "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""` due to (pid=1895277, name='ray::ClientAppActor.run')
2024-07-01 01:55:18,642	ERR scripts.py:1127 -- Could not terminate `ray::ClientAppActor.run "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""` due to (pid=1895278, name='ray::ClientAppActor.run')
2024-07-01 01:55:18,648	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=32 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,accelerator_type:G,1,CPU,32,memory,150123589428,object_store_memory,68624395468 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --redis-address=None --temp-dir=/tmp/ray --metrics-agent-port=59027 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --temp-dir=/tmp/ray --webui= RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:52383 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs -Dray.session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --log_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --resource_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --metrics-agent-port=59027 --metrics_export_port=53174 --object_store_memory=68624395468 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --labels= --head --num_prestart_python_workers=32 "--agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=53174 --dashboard-agent-port=59027 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --runtime-env-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --log-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-30_20-02-14_305409_1614546 --gcs-address=10.20.240.18:52383 --minimal"` due to (pid=1614755, name='raylet')
2024-07-01 01:55:18,649	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=2 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,CPU,2,memory,164658337997,object_store_memory,74853573427 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --redis-address=None --metrics-agent-port=46078 --runtime-env-agent-port=58341 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --temp-dir=/tmp/ray --webui= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:47294 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs -Dray.session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --resource_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --metrics-agent-port=46078 --metrics_export_port=61221 --runtime_env_agent_port=58341 --object_store_memory=74853573427 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --labels= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 --head --num_prestart_python_workers=2 "--dashboard_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=61221 --dashboard-agent-port=46078 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-28_07-48-43_813905_1894806 --gcs-address=10.20.240.18:47294 --minimal" "--runtime_env_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=10.20.240.18 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --runtime-env-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --temp-dir=/tmp/ray"` due to (pid=1894993, name='raylet')
2024-07-01 01:55:18,653	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/log_monitor.py --logs-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --gcs-address=10.20.240.18:52383 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5` due to (pid=1614784, name='python3')
2024-07-01 01:55:18,654	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/log_monitor.py --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --logs-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --gcs-address=10.20.240.18:47294 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5` due to (pid=1895026, name='python3')
2024-07-01 01:55:18,663	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=32 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,accelerator_type:G,1,CPU,32,memory,150123589428,object_store_memory,68624395468 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --redis-address=None --temp-dir=/tmp/ray --metrics-agent-port=59027 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --temp-dir=/tmp/ray --webui= RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:52383 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs -Dray.session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --log_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --resource_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --metrics-agent-port=59027 --metrics_export_port=53174 --object_store_memory=68624395468 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --labels= --head --num_prestart_python_workers=32 "--agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=53174 --dashboard-agent-port=59027 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --runtime-env-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --log-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-30_20-02-14_305409_1614546 --gcs-address=10.20.240.18:52383 --minimal"` due to (pid=1614755, name='raylet')
2024-07-01 01:55:18,664	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=53174 --dashboard-agent-port=59027 --listen-port=52365 --node-manager-port=45039 --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --runtime-env-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --log-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-30_20-02-14_305409_1614546 --gcs-address=10.20.240.18:52383 --minimal --agent-id 424238335` due to (pid=1614816, name='python3')
2024-07-01 01:55:18,664	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=2 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,CPU,2,memory,164658337997,object_store_memory,74853573427 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --redis-address=None --metrics-agent-port=46078 --runtime-env-agent-port=58341 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --temp-dir=/tmp/ray --webui= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:47294 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs -Dray.session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --resource_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --metrics-agent-port=46078 --metrics_export_port=61221 --runtime_env_agent_port=58341 --object_store_memory=74853573427 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --labels= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 --head --num_prestart_python_workers=2 "--dashboard_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=61221 --dashboard-agent-port=46078 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-28_07-48-43_813905_1894806 --gcs-address=10.20.240.18:47294 --minimal" "--runtime_env_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=10.20.240.18 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --runtime-env-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --temp-dir=/tmp/ray"` due to (pid=1894993, name='raylet')
2024-07-01 01:55:18,665	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=61221 --dashboard-agent-port=46078 --listen-port=52365 --node-manager-port=43953 --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-28_07-48-43_813905_1894806 --gcs-address=10.20.240.18:47294 --minimal --agent-id 424238335` due to (pid=1895073, name='python3')
2024-07-01 01:55:18,670	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/dashboard.py --host=127.0.0.1 --port=8265 --port-retries=50 --temp-dir=/tmp/ray --log-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:52383 --node-ip-address=10.20.240.18 --minimal` due to (pid=1614716, name='python3')
2024-07-01 01:55:18,670	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/dashboard.py --host=127.0.0.1 --port=8265 --port-retries=50 --temp-dir=/tmp/ray --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:47294 --node-ip-address=10.20.240.18 --minimal` due to (pid=1894944, name='python3')
2024-07-01 01:55:18,675	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=2 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,CPU,2,memory,164658337997,object_store_memory,74853573427 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --redis-address=None --metrics-agent-port=46078 --runtime-env-agent-port=58341 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --temp-dir=/tmp/ray --webui= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:47294 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs -Dray.session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --resource_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --metrics-agent-port=46078 --metrics_export_port=61221 --runtime_env_agent_port=58341 --object_store_memory=74853573427 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --labels= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 --head --num_prestart_python_workers=2 "--dashboard_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=61221 --dashboard-agent-port=46078 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-28_07-48-43_813905_1894806 --gcs-address=10.20.240.18:47294 --minimal" "--runtime_env_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=10.20.240.18 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --runtime-env-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --temp-dir=/tmp/ray"` due to (pid=1894993, name='raylet')
2024-07-01 01:55:18,675	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=10.20.240.18 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --runtime-env-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --temp-dir=/tmp/ray` due to (pid=1895075, name='python3')
2024-07-01 01:55:18,783	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --config_list=eyJvYmplY3Rfc3BpbGxpbmdfY29uZmlnIjogIntcInR5cGVcIjogXCJmaWxlc3lzdGVtXCIsIFwicGFyYW1zXCI6IHtcImRpcmVjdG9yeV9wYXRoXCI6IFwiL3RtcC9yYXkvc2Vzc2lvbl8yMDI0LTA2LTMwXzIwLTAyLTE0XzMwNTQwOV8xNjE0NTQ2XCJ9fSIsICJpc19leHRlcm5hbF9zdG9yYWdlX3R5cGVfZnMiOiB0cnVlfQ== --gcs_server_port=52383 --metrics-agent-port=59027 --node-ip-address=10.20.240.18 --session-name=session_2024-06-30_20-02-14_305409_1614546` due to (pid=1614631, name='gcs_server')
2024-07-01 01:55:18,784	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --config_list=eyJvYmplY3Rfc3BpbGxpbmdfY29uZmlnIjogIntcInR5cGVcIjogXCJmaWxlc3lzdGVtXCIsIFwicGFyYW1zXCI6IHtcImRpcmVjdG9yeV9wYXRoXCI6IFwiL3RtcC9yYXkvc2Vzc2lvbl8yMDI0LTA2LTI4XzA3LTQ4LTQzXzgxMzkwNV8xODk0ODA2XCJ9fSIsICJpc19leHRlcm5hbF9zdG9yYWdlX3R5cGVfZnMiOiB0cnVlfQ== --gcs_server_port=47294 --metrics-agent-port=46078 --node-ip-address=10.20.240.18 --session-name=session_2024-06-28_07-48-43_813905_1894806` due to (pid=1894828, name='gcs_server')
2024-07-01 01:55:18,784	INFO scripts.py:1186 -- Did not find any active Ray processes.
2024-07-01 01:55:19,877	INFO usage_lib.py:472 -- Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.
2024-07-01 01:55:19,877	INFO scripts.py:767 -- Local node IP: 10.20.240.18
2024-07-01 01:55:23,608	SUCC scripts.py:804 -- --------------------
2024-07-01 01:55:23,608	SUCC scripts.py:805 -- Ray runtime started.
2024-07-01 01:55:23,608	SUCC scripts.py:806 -- --------------------
2024-07-01 01:55:23,608	INFO scripts.py:808 -- Next steps
2024-07-01 01:55:23,608	INFO scripts.py:811 -- To add another node to this Ray cluster, run
2024-07-01 01:55:23,608	INFO scripts.py:814 --   ray start --address='10.20.240.18:6379'
2024-07-01 01:55:23,608	INFO scripts.py:823 -- To connect to this Ray cluster:
2024-07-01 01:55:23,608	INFO scripts.py:825 -- import ray
2024-07-01 01:55:23,608	INFO scripts.py:826 -- ray.init()
2024-07-01 01:55:23,608	INFO scripts.py:857 -- To terminate the Ray runtime, run
2024-07-01 01:55:23,609	INFO scripts.py:858 --   ray stop
2024-07-01 01:55:23,609	INFO scripts.py:861 -- To view the status of the cluster, use
2024-07-01 01:55:23,609	INFO scripts.py:862 --   ray status
2024-07-01 01:55:28.020420: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-01 01:55:28.621556: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-01 01:55:30.591909: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
INFO flwr 2024-07-01 01:55:39,766 | Data.py:36 | Preprocessing the federated learning dataset
INFO flwr 2024-07-01 01:55:39,768 | Data.py:111 | Found preprocessed data for the given preprocess function with hash 6953241a9b8ff95102b78518189c2b990449e30cf33ece85878cd0da48066bd8, returning
INFO flwr 2024-07-01 01:55:40,192 | Simulation.py:38 | Preparing datasets for federated learning simulation
INFO flwr 2024-07-01 01:55:40,193 | Simulation.py:274 | Found previously split dataloaders with hash 3135f4a9fd34f3f9a9034f75ff877a4639f862996466129c434222b61345c35b, loading them
INFO flwr 2024-07-01 01:55:43,637 | main.py:111 | Loaded 1 configs with name TEXAS-LOG_RES-FEDNL, running...
INFO flwr 2024-07-01 01:55:43,641 | main.py:113 | Config:
	Simulation:
		Data:
			dataset_name: texas
			batch_size: -1
			preprocess_fn:
				def preprocess_fn(element):
				  return {
				    "x": element["features"],
				    "y": element["label"]
				  }
		Federation:
			client_count: 10
			fraction_fit: 1.0
			local_rounds: 1
		Model:
			optimizer_name: SingleLayerFedNL
			model_name: Logistic Regression
			criterion_name: CrossEntropyLoss
			optimizer_parameters: 
				
			model_architecture:
				type: Linear
					in_features: 6169
					out_features: 100
	Attack:
		data_access: 1.0
		message_access: server
		aggregate_access: 1
		repetitions: 0
		Attack Simulation:
			batch_size: 64
			optimizer_name: Adam
			optimizer_parameters:
				eps: 0.0001
			ModelArchitecture:
				components:
					label: True
					loss: True
					activation: False
					gradient: False
					metrics: False
				gradient_component:
					type: Dropout
						p: 0.2
					type: Conv2d
						out_channels: 1000
						kernel_size: None
						stride: 1
					type: ReLU
				fcn_component:
					type: Dropout
						p: 0.2
					type: Linear
						out_features: 128
					type: ReLU
					type: Dropout
						p: 0.2
					type: Linear
						in_features: 128
						out_features: 64
					type: ReLU
				encoder_component:
					type: Dropout
						p: 0.2
					type: Linear
						out_features: 256
					type: ReLU
					type: Dropout
						p: 0.2
					type: Linear
						in_features: 256
						out_features: 128
					type: ReLU
					type: Dropout
						p: 0.2
					type: Linear
						in_features: 128
						out_features: 64
					type: ReLU
					type: Dropout
						p: 0.2
					type: Linear
						in_features: 64
						out_features: 1
					type: ReLU
INFO flwr 2024-07-01 01:55:43,641 | Config.py:69 | Starting conFEDential simulation
INFO flwr 2024-07-01 01:55:43,643 | Config.py:74 | No previous federated learning simulation found with hash dd23465b622e9859947fce3be023a1db26fe54c93c0cb4f6e49e4125a4f09026, starting training simulation...
wandb: Tracking run with wandb version 0.17.1
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
INFO flwr 2024-07-01 01:55:45,798 | Simulation.py:417 | Created 1 clients with resources 4 CPUs, 4.0 GPUs, and 32.0GB for the total available 4 CPUs, 4 GPUs and 32.0GB.
INFO flwr 2024-07-01 01:55:45,800 | Simulation.py:166 | Starting federated learning simulation
2024-07-01 01:55:45,860	WARNING services.py:408 -- Found multiple active Ray instances: {'10.20.240.18:6379', '10.20.240.18:47294', '10.20.240.18:52383'}. Connecting to latest cluster at 10.20.240.18:6379. You can override this by setting the `--address` flag or `RAY_ADDRESS` environment variable.
2024-07-01 01:55:45,860	INFO worker.py:1586 -- Connecting to existing Ray cluster at address: 10.20.240.18:6379...
2024-07-01 01:55:45,870	INFO worker.py:1771 -- Connected to Ray cluster.
INFO flwr 2024-07-01 01:55:46,901 | app.py:178 | Starting Flower simulation, config: ServerConfig(num_rounds=10000, round_timeout=None)
2024-07-01 01:55:47,025	INFO worker.py:1604 -- Calling ray.init() again after it has already been called.
INFO flwr 2024-07-01 01:55:47,026 | app.py:213 | Flower VCE: Ray initialized with resources: {'accelerator_type:G': 1.0, 'node:__internal_head__': 1.0, 'node:10.20.240.18': 1.0, 'CPU': 4.0, 'object_store_memory': 67097761382.0, 'memory': 36507222016.0, 'GPU': 4.0}
INFO flwr 2024-07-01 01:55:47,027 | app.py:219 | Optimize your simulation with Flower VCE: https://flower.dev/docs/framework/how-to-run-simulations.html
INFO flwr 2024-07-01 01:55:47,027 | app.py:242 | Flower VCE: Resources for each Virtual Client: {'num_cpus': 4, 'num_gpus': 4.0, 'memory': 34359738368}
INFO flwr 2024-07-01 01:55:47,045 | app.py:288 | Flower VCE: Creating VirtualClientEngineActorPool with 1 actors
INFO flwr 2024-07-01 01:55:47,046 | server.py:88 | Initializing global parameters
INFO flwr 2024-07-01 01:55:47,047 | server.py:295 | Using initial parameters provided by strategy
INFO flwr 2024-07-01 01:55:47,047 | server.py:90 | Evaluating initial parameters
[36m(pid=1697276)[0m 2024-07-01 01:55:48.410164: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[36m(pid=1697276)[0m 2024-07-01 01:55:48.472439: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[36m(pid=1697276)[0m To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO flwr 2024-07-01 01:55:49,471 | server.py:93 | initial parameters (loss, other metrics): 4.605998828125, {'accuracy': 0.0084, 'data_size': 2500}
INFO flwr 2024-07-01 01:55:49,471 | server.py:103 | FL starting
DEBUG flwr 2024-07-01 01:55:49,472 | server.py:245 | fit_round 1: strategy sampled 10 clients (out of 10)
[36m(pid=1697276)[0m 2024-07-01 01:55:49.877694: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
DEBUG flwr 2024-07-01 01:57:00,776 | server.py:259 | fit_round 1 received 10 results and 0 failures
INFO flwr 2024-07-01 03:52:20,088 | server.py:131 | fit progress: (1, 3.0360388671875, {'accuracy': 0.5312, 'data_size': 2500}, 6990.616478765383)
DEBUG flwr 2024-07-01 03:52:20,089 | server.py:146 | Loss decrease: 0.3408511420695684
INFO flwr 2024-07-01 03:52:20,090 | server.py:194 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2024-07-01 03:52:20,090 | server.py:245 | fit_round 2: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 03:53:26,291 | server.py:259 | fit_round 2 received 10 results and 0 failures
INFO flwr 2024-07-01 05:05:06,044 | server.py:131 | fit progress: (2, 2.5223, {'accuracy': 0.5264, 'data_size': 2500}, 11356.572680154815)
DEBUG flwr 2024-07-01 05:05:06,045 | server.py:146 | Loss decrease: 0.16921353436539274
INFO flwr 2024-07-01 05:05:06,045 | server.py:194 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2024-07-01 05:05:06,045 | server.py:245 | fit_round 3: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 05:06:05,268 | server.py:259 | fit_round 3 received 10 results and 0 failures
INFO flwr 2024-07-01 06:15:40,381 | server.py:131 | fit progress: (3, 2.4397162109375, {'accuracy': 0.522, 'data_size': 2500}, 15590.909869014286)
DEBUG flwr 2024-07-01 06:15:40,382 | server.py:146 | Loss decrease: 0.03274146178586998
INFO flwr 2024-07-01 06:15:40,382 | server.py:194 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2024-07-01 06:15:40,382 | server.py:245 | fit_round 4: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 06:16:40,374 | server.py:259 | fit_round 4 received 10 results and 0 failures
INFO flwr 2024-07-01 07:26:15,658 | server.py:131 | fit progress: (4, 2.6703576171875, {'accuracy': 0.5096, 'data_size': 2500}, 19826.186032525264)
DEBUG flwr 2024-07-01 07:26:15,658 | server.py:146 | Loss decrease: -0.0945361617125838
INFO flwr 2024-07-01 07:26:15,658 | server.py:194 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2024-07-01 07:26:15,658 | server.py:245 | fit_round 5: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 07:27:15,596 | server.py:259 | fit_round 5 received 10 results and 0 failures
INFO flwr 2024-07-01 08:37:05,982 | server.py:131 | fit progress: (5, 3.098181640625, {'accuracy': 0.4996, 'data_size': 2500}, 24076.510461170226)
DEBUG flwr 2024-07-01 08:37:05,982 | server.py:146 | Loss decrease: -0.16021225797018795
INFO flwr 2024-07-01 08:37:05,983 | server.py:194 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2024-07-01 08:37:05,983 | server.py:245 | fit_round 6: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 08:38:06,101 | server.py:259 | fit_round 6 received 10 results and 0 failures
INFO flwr 2024-07-01 09:49:00,724 | server.py:131 | fit progress: (6, 3.6392609375, {'accuracy': 0.4924, 'data_size': 2500}, 28391.25236767903)
DEBUG flwr 2024-07-01 09:49:00,724 | server.py:146 | Loss decrease: -0.1746441492584171
INFO flwr 2024-07-01 09:49:00,724 | server.py:194 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2024-07-01 09:49:00,725 | server.py:245 | fit_round 7: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 09:50:01,917 | server.py:259 | fit_round 7 received 10 results and 0 failures
INFO flwr 2024-07-01 11:01:05,209 | server.py:131 | fit progress: (7, 4.22597265625, {'accuracy': 0.482, 'data_size': 2500}, 32715.737591288984)
DEBUG flwr 2024-07-01 11:01:05,210 | server.py:146 | Loss decrease: -0.16121727153564397
INFO flwr 2024-07-01 11:01:05,210 | server.py:194 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2024-07-01 11:01:05,210 | server.py:245 | fit_round 8: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 11:02:04,797 | server.py:259 | fit_round 8 received 10 results and 0 failures
INFO flwr 2024-07-01 12:13:25,379 | server.py:131 | fit progress: (8, 4.799441015625, {'accuracy': 0.4788, 'data_size': 2500}, 37055.907147415914)
DEBUG flwr 2024-07-01 12:13:25,379 | server.py:146 | Loss decrease: -0.13570091574702203
INFO flwr 2024-07-01 12:13:25,379 | server.py:194 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2024-07-01 12:13:25,379 | server.py:245 | fit_round 9: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 12:14:25,433 | server.py:259 | fit_round 9 received 10 results and 0 failures
INFO flwr 2024-07-01 13:25:26,808 | server.py:131 | fit progress: (9, 5.31725703125, {'accuracy': 0.4752, 'data_size': 2500}, 41377.33608312346)
DEBUG flwr 2024-07-01 13:25:26,808 | server.py:146 | Loss decrease: -0.10789090103185027
INFO flwr 2024-07-01 13:25:26,808 | server.py:194 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2024-07-01 13:25:26,808 | server.py:245 | fit_round 10: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 13:26:26,298 | server.py:259 | fit_round 10 received 10 results and 0 failures
INFO flwr 2024-07-01 14:37:28,239 | server.py:131 | fit progress: (10, 5.763889453125, {'accuracy': 0.4736, 'data_size': 2500}, 45698.767731186934)
DEBUG flwr 2024-07-01 14:37:28,240 | server.py:146 | Loss decrease: -0.08399677112656034
INFO flwr 2024-07-01 14:37:28,240 | server.py:194 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2024-07-01 14:37:28,240 | server.py:245 | fit_round 11: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 14:38:27,737 | server.py:259 | fit_round 11 received 10 results and 0 failures
INFO flwr 2024-07-01 15:49:33,539 | server.py:131 | fit progress: (11, 6.1388875, {'accuracy': 0.4776, 'data_size': 2500}, 50024.06770174764)
DEBUG flwr 2024-07-01 15:49:33,540 | server.py:146 | Loss decrease: -0.06505989573961873
INFO flwr 2024-07-01 15:49:33,540 | server.py:194 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2024-07-01 15:49:33,540 | server.py:245 | fit_round 12: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 15:50:34,123 | server.py:259 | fit_round 12 received 10 results and 0 failures
INFO flwr 2024-07-01 17:01:39,807 | server.py:131 | fit progress: (12, 6.45328515625, {'accuracy': 0.478, 'data_size': 2500}, 54350.335601112805)
DEBUG flwr 2024-07-01 17:01:39,808 | server.py:146 | Loss decrease: -0.05121410943758127
INFO flwr 2024-07-01 17:01:39,808 | server.py:194 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2024-07-01 17:01:39,808 | server.py:245 | fit_round 13: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 17:02:41,680 | server.py:259 | fit_round 13 received 10 results and 0 failures
INFO flwr 2024-07-01 18:13:32,773 | server.py:131 | fit progress: (13, 6.72074609375, {'accuracy': 0.4772, 'data_size': 2500}, 58663.30105056614)
DEBUG flwr 2024-07-01 18:13:32,773 | server.py:146 | Loss decrease: -0.04144570261876069
INFO flwr 2024-07-01 18:13:32,773 | server.py:194 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2024-07-01 18:13:32,774 | server.py:245 | fit_round 14: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 18:14:33,934 | server.py:259 | fit_round 14 received 10 results and 0 failures
INFO flwr 2024-07-01 19:30:45,558 | server.py:131 | fit progress: (14, 6.95210625, {'accuracy': 0.4776, 'data_size': 2500}, 63296.08635286242)
DEBUG flwr 2024-07-01 19:30:45,558 | server.py:146 | Loss decrease: -0.03442477264022143
INFO flwr 2024-07-01 19:30:45,559 | server.py:194 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2024-07-01 19:30:45,559 | server.py:245 | fit_round 15: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 19:31:52,446 | server.py:259 | fit_round 15 received 10 results and 0 failures
INFO flwr 2024-07-01 20:49:48,284 | server.py:131 | fit progress: (15, 7.155246875, {'accuracy': 0.4756, 'data_size': 2500}, 68038.81227398105)
DEBUG flwr 2024-07-01 20:49:48,284 | server.py:146 | Loss decrease: -0.029220011561244427
INFO flwr 2024-07-01 20:49:48,284 | server.py:194 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2024-07-01 20:49:48,285 | server.py:245 | fit_round 16: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 20:50:56,644 | server.py:259 | fit_round 16 received 10 results and 0 failures
INFO flwr 2024-07-01 22:08:23,780 | server.py:131 | fit progress: (16, 7.33600390625, {'accuracy': 0.4756, 'data_size': 2500}, 72754.30823334306)
DEBUG flwr 2024-07-01 22:08:23,780 | server.py:146 | Loss decrease: -0.025262165569933694
INFO flwr 2024-07-01 22:08:23,780 | server.py:194 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2024-07-01 22:08:23,781 | server.py:245 | fit_round 17: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 22:09:33,408 | server.py:259 | fit_round 17 received 10 results and 0 failures
INFO flwr 2024-07-01 23:27:13,238 | server.py:131 | fit progress: (17, 7.49869765625, {'accuracy': 0.4748, 'data_size': 2500}, 77483.76685906202)
DEBUG flwr 2024-07-01 23:27:13,239 | server.py:146 | Loss decrease: -0.022177435028543385
INFO flwr 2024-07-01 23:27:13,239 | server.py:194 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2024-07-01 23:27:13,239 | server.py:245 | fit_round 18: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-01 23:28:20,722 | server.py:259 | fit_round 18 received 10 results and 0 failures
INFO flwr 2024-07-02 00:46:48,854 | server.py:131 | fit progress: (18, 7.6465703125, {'accuracy': 0.4732, 'data_size': 2500}, 82259.38288368564)
DEBUG flwr 2024-07-02 00:46:48,855 | server.py:146 | Loss decrease: -0.019719778424024212
INFO flwr 2024-07-02 00:46:48,855 | server.py:194 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2024-07-02 00:46:48,855 | server.py:245 | fit_round 19: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-02 00:47:55,074 | server.py:259 | fit_round 19 received 10 results and 0 failures
INFO flwr 2024-07-02 02:06:25,900 | server.py:131 | fit progress: (19, 7.78209765625, {'accuracy': 0.4736, 'data_size': 2500}, 87036.42809044477)
DEBUG flwr 2024-07-02 02:06:25,900 | server.py:146 | Loss decrease: -0.01772393873478825
INFO flwr 2024-07-02 02:06:25,900 | server.py:194 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2024-07-02 02:06:25,901 | server.py:245 | fit_round 20: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-02 02:07:34,420 | server.py:259 | fit_round 20 received 10 results and 0 failures
INFO flwr 2024-07-02 03:20:24,267 | server.py:131 | fit progress: (20, 7.907221875, {'accuracy': 0.4724, 'data_size': 2500}, 91474.79571518116)
DEBUG flwr 2024-07-02 03:20:24,268 | server.py:146 | Loss decrease: -0.016078469363528157
INFO flwr 2024-07-02 03:20:24,268 | server.py:194 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2024-07-02 03:20:24,268 | server.py:245 | fit_round 21: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-02 03:21:24,991 | server.py:259 | fit_round 21 received 10 results and 0 failures
INFO flwr 2024-07-02 04:32:54,754 | server.py:131 | fit progress: (21, 8.02346328125, {'accuracy': 0.4732, 'data_size': 2500}, 95825.28220299818)
DEBUG flwr 2024-07-02 04:32:54,754 | server.py:146 | Loss decrease: -0.014700663278150436
INFO flwr 2024-07-02 04:32:54,754 | server.py:194 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2024-07-02 04:32:54,754 | server.py:245 | fit_round 22: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-02 04:33:54,718 | server.py:259 | fit_round 22 received 10 results and 0 failures
INFO flwr 2024-07-02 05:45:30,589 | server.py:131 | fit progress: (22, 8.13200625, {'accuracy': 0.474, 'data_size': 2500}, 100181.11712405924)
DEBUG flwr 2024-07-02 05:45:30,589 | server.py:146 | Loss decrease: -0.01352819411583186
INFO flwr 2024-07-02 05:45:30,589 | server.py:194 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2024-07-02 05:45:30,589 | server.py:245 | fit_round 23: strategy sampled 10 clients (out of 10)
DEBUG flwr 2024-07-02 05:46:29,885 | server.py:259 | fit_round 23 received 10 results and 0 failures
INFO flwr 2024-07-02 06:59:30,820 | server.py:131 | fit progress: (23, 8.2338, {'accuracy': 0.474, 'data_size': 2500}, 104621.34891371336)
DEBUG flwr 2024-07-02 06:59:30,821 | server.py:146 | Loss decrease: -0.012517667457523238
INFO flwr 2024-07-02 06:59:30,821 | server.py:194 | evaluate_round 23: no clients selected, cancel
INFO flwr 2024-07-02 06:59:30,821 | server.py:163 | Early stopping at round 23, loss: 8.2338
INFO flwr 2024-07-02 06:59:30,821 | server.py:176 | FL finished in 104621.34982113913
INFO flwr 2024-07-02 06:59:30,837 | app.py:226 | app_fit: losses_distributed []
INFO flwr 2024-07-02 06:59:30,837 | app.py:228 | app_fit: metrics_distributed {}
INFO flwr 2024-07-02 06:59:30,838 | app.py:229 | app_fit: losses_centralized [(0, 4.605998828125), (1, 3.0360388671875), (2, 2.5223), (3, 2.4397162109375), (4, 2.6703576171875), (5, 3.098181640625), (6, 3.6392609375), (7, 4.22597265625), (8, 4.799441015625), (9, 5.31725703125), (10, 5.763889453125), (11, 6.1388875), (12, 6.45328515625), (13, 6.72074609375), (14, 6.95210625), (15, 7.155246875), (16, 7.33600390625), (17, 7.49869765625), (18, 7.6465703125), (19, 7.78209765625), (20, 7.907221875), (21, 8.02346328125), (22, 8.13200625), (23, 8.2338)]
INFO flwr 2024-07-02 06:59:30,838 | app.py:230 | app_fit: metrics_centralized {'accuracy': [(0, 0.0084), (1, 0.5312), (2, 0.5264), (3, 0.522), (4, 0.5096), (5, 0.4996), (6, 0.4924), (7, 0.482), (8, 0.4788), (9, 0.4752), (10, 0.4736), (11, 0.4776), (12, 0.478), (13, 0.4772), (14, 0.4776), (15, 0.4756), (16, 0.4756), (17, 0.4748), (18, 0.4732), (19, 0.4736), (20, 0.4724), (21, 0.4732), (22, 0.474), (23, 0.474)], 'data_size': [(0, 2500), (1, 2500), (2, 2500), (3, 2500), (4, 2500), (5, 2500), (6, 2500), (7, 2500), (8, 2500), (9, 2500), (10, 2500), (11, 2500), (12, 2500), (13, 2500), (14, 2500), (15, 2500), (16, 2500), (17, 2500), (18, 2500), (19, 2500), (20, 2500), (21, 2500), (22, 2500), (23, 2500)]}
wandb: - 0.000 MB of 0.000 MB uploadedwandb:                                                                                
wandb: 
wandb: Run summary:
wandb: accuracy 0.474
wandb:     loss 8.2338
wandb: 
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /home/s2240084/conFEDential/wandb/offline-run-20240701_015544-qng8y8af
wandb: Find logs at: ./wandb/offline-run-20240701_015544-qng8y8af/logs
2024-07-02 07:05:24,988	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=32 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,accelerator_type:G,1,CPU,32,memory,150123589428,object_store_memory,68624395468 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --redis-address=None --temp-dir=/tmp/ray --metrics-agent-port=59027 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --temp-dir=/tmp/ray --webui= RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:52383 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs -Dray.session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --log_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --resource_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --metrics-agent-port=59027 --metrics_export_port=53174 --object_store_memory=68624395468 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --labels= --head --num_prestart_python_workers=32 "--agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=53174 --dashboard-agent-port=59027 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --runtime-env-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --log-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-30_20-02-14_305409_1614546 --gcs-address=10.20.240.18:52383 --minimal"` due to (pid=1614755, name='raylet')
2024-07-02 07:05:24,988	VINFO scripts.py:1114 -- Send termination request to `/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/local/ray/session_2024-07-01_01-55-19_924071_1695969/sockets/raylet --store_socket_name=/local/ray/session_2024-07-01_01-55-19_924071_1695969/sockets/plasma_store --object_manager_port=0 --min_worker_port=10002 --max_worker_port=19999 --node_manager_port=0 --node_id=b1cb3dd390dcde663c11dc68f9348ad72256e24ca1c773ac2161af5f --node_ip_address=10.20.240.18 --maximum_startup_concurrency=4 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,accelerator_type:G,1,CPU,4,GPU,4,memory,36507222016,object_store_memory,67097761382 "--python_worker_command=/home/s2240084/conFEDential/venv/bin/python /home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/local/ray/session_2024-07-01_01-55-19_924071_1695969/sockets/plasma_store --raylet-name=/local/ray/session_2024-07-01_01-55-19_924071_1695969/sockets/raylet --redis-address=None --metrics-agent-port=48709 --runtime-env-agent-port=42914 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --runtime-env-agent-port=42914 --gcs-address=10.20.240.18:6379 --session-name=session_2024-07-01_01-55-19_924071_1695969 --temp-dir=/local/ray --webui= --cluster-id=bd7501f350dd257f14b8a52e599a3ff79ac4008e0a5c11f80e0a5c79 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/home/s2240084/conFEDential/venv/bin/python /home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:6379 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/local/ray/session_2024-07-01_01-55-19_924071_1695969/sockets/plasma_store -Dray.raylet.socket-name=/local/ray/session_2024-07-01_01-55-19_924071_1695969/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969/logs -Dray.session-dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/local/ray --session_dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969 --log_dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969/logs --resource_dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969/runtime_resources --metrics-agent-port=48709 --metrics_export_port=61670 --runtime_env_agent_port=42914 --object_store_memory=67097761382 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:6379 --session-name=session_2024-07-01_01-55-19_924071_1695969 --labels= --cluster-id=bd7501f350dd257f14b8a52e599a3ff79ac4008e0a5c11f80e0a5c79 --head --num_prestart_python_workers=4 "--dashboard_agent_command=/home/s2240084/conFEDential/venv/bin/python -u /home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=61670 --dashboard-agent-port=48709 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/local/ray/session_2024-07-01_01-55-19_924071_1695969/sockets/plasma_store --raylet-name=/local/ray/session_2024-07-01_01-55-19_924071_1695969/sockets/raylet --temp-dir=/local/ray --session-dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969 --log-dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-07-01_01-55-19_924071_1695969 --gcs-address=10.20.240.18:6379 --minimal" "--runtime_env_agent_command=/home/s2240084/conFEDential/venv/bin/python -u /home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=10.20.240.18 --runtime-env-agent-port=42914 --gcs-address=10.20.240.18:6379 --runtime-env-dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969/logs --temp-dir=/local/ray"` (via SIGTERM)
2024-07-02 07:05:24,989	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=2 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,CPU,2,memory,164658337997,object_store_memory,74853573427 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --redis-address=None --metrics-agent-port=46078 --runtime-env-agent-port=58341 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --temp-dir=/tmp/ray --webui= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:47294 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs -Dray.session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --resource_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --metrics-agent-port=46078 --metrics_export_port=61221 --runtime_env_agent_port=58341 --object_store_memory=74853573427 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --labels= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 --head --num_prestart_python_workers=2 "--dashboard_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=61221 --dashboard-agent-port=46078 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-28_07-48-43_813905_1894806 --gcs-address=10.20.240.18:47294 --minimal" "--runtime_env_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=10.20.240.18 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --runtime-env-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --temp-dir=/tmp/ray"` due to (pid=1894993, name='raylet')
2024-07-02 07:05:25,323	INFO scripts.py:1144 -- 1/1 stopped.2024-07-02 07:05:25,438	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/autoscaler/_private/monitor.py --logs-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:52383 --monitor-ip=10.20.240.18` due to (pid=1614715, name='python3')
2024-07-02 07:05:25,438	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/log_monitor.py --logs-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --gcs-address=10.20.240.18:52383 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5` due to (pid=1614784, name='python3')
2024-07-02 07:05:25,438	VINFO scripts.py:1114 -- Send termination request to `/home/s2240084/conFEDential/venv/bin/python -u /home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/autoscaler/_private/monitor.py --logs-dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:6379 --monitor-ip=10.20.240.18` (via SIGTERM)
2024-07-02 07:05:25,439	VINFO scripts.py:1114 -- Send termination request to `/home/s2240084/conFEDential/venv/bin/python -u /home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/_private/log_monitor.py --session-dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969 --logs-dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969/logs --gcs-address=10.20.240.18:6379 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5` (via SIGTERM)
2024-07-02 07:05:25,439	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/autoscaler/_private/monitor.py --logs-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:47294 --monitor-ip=10.20.240.18` due to (pid=1894943, name='python3')
2024-07-02 07:05:25,439	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/log_monitor.py --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --logs-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --gcs-address=10.20.240.18:47294 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5` due to (pid=1895026, name='python3')
2024-07-02 07:05:25,445	VINFO scripts.py:1114 -- Send termination request to `/home/s2240084/conFEDential/venv/bin/python -m ray.util.client.server --address=10.20.240.18:6379 --host=0.0.0.0 --port=10001 --mode=proxy --runtime-env-agent-address=http://10.20.240.18:42914` (via SIGTERM)
2024-07-02 07:05:25,450	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=32 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,accelerator_type:G,1,CPU,32,memory,150123589428,object_store_memory,68624395468 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --redis-address=None --temp-dir=/tmp/ray --metrics-agent-port=59027 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --temp-dir=/tmp/ray --webui= RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:52383 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs -Dray.session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --log_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --resource_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --metrics-agent-port=59027 --metrics_export_port=53174 --object_store_memory=68624395468 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --labels= --head --num_prestart_python_workers=32 "--agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=53174 --dashboard-agent-port=59027 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --runtime-env-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --log-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-30_20-02-14_305409_1614546 --gcs-address=10.20.240.18:52383 --minimal"` due to (pid=1614755, name='raylet')
2024-07-02 07:05:25,451	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=2 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,CPU,2,memory,164658337997,object_store_memory,74853573427 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --redis-address=None --metrics-agent-port=46078 --runtime-env-agent-port=58341 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --temp-dir=/tmp/ray --webui= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:47294 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs -Dray.session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --resource_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --metrics-agent-port=46078 --metrics_export_port=61221 --runtime_env_agent_port=58341 --object_store_memory=74853573427 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --labels= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 --head --num_prestart_python_workers=2 "--dashboard_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=61221 --dashboard-agent-port=46078 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-28_07-48-43_813905_1894806 --gcs-address=10.20.240.18:47294 --minimal" "--runtime_env_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=10.20.240.18 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --runtime-env-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --temp-dir=/tmp/ray"` due to (pid=1894993, name='raylet')
2024-07-02 07:05:25,456	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=32 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,accelerator_type:G,1,CPU,32,memory,150123589428,object_store_memory,68624395468 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --redis-address=None --temp-dir=/tmp/ray --metrics-agent-port=59027 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --temp-dir=/tmp/ray --webui= RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:52383 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs -Dray.session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --log_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --resource_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --metrics-agent-port=59027 --metrics_export_port=53174 --object_store_memory=68624395468 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --labels= --head --num_prestart_python_workers=32 "--agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=53174 --dashboard-agent-port=59027 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --runtime-env-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --log-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-30_20-02-14_305409_1614546 --gcs-address=10.20.240.18:52383 --minimal"` due to (pid=1614755, name='raylet')
2024-07-02 07:05:25,457	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=2 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,CPU,2,memory,164658337997,object_store_memory,74853573427 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --redis-address=None --metrics-agent-port=46078 --runtime-env-agent-port=58341 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --temp-dir=/tmp/ray --webui= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:47294 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs -Dray.session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --resource_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --metrics-agent-port=46078 --metrics_export_port=61221 --runtime_env_agent_port=58341 --object_store_memory=74853573427 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --labels= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 --head --num_prestart_python_workers=2 "--dashboard_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=61221 --dashboard-agent-port=46078 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-28_07-48-43_813905_1894806 --gcs-address=10.20.240.18:47294 --minimal" "--runtime_env_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=10.20.240.18 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --runtime-env-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --temp-dir=/tmp/ray"` due to (pid=1894993, name='raylet')
2024-07-02 07:05:25,458	ERR scripts.py:1127 -- Could not terminate `ray::ClientAppActor.run "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""` due to (pid=1615491, name='ray::ClientAppActor.run')
2024-07-02 07:05:25,458	ERR scripts.py:1127 -- Could not terminate `ray::ClientAppActor.run "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""` due to (pid=1615492, name='ray::ClientAppActor.run')
2024-07-02 07:05:25,459	ERR scripts.py:1127 -- Could not terminate `ray::ClientAppActor.run "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""` due to (pid=1895277, name='ray::ClientAppActor.run')
2024-07-02 07:05:25,459	ERR scripts.py:1127 -- Could not terminate `ray::ClientAppActor.run "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""` due to (pid=1895278, name='ray::ClientAppActor.run')
2024-07-02 07:05:25,464	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=32 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,accelerator_type:G,1,CPU,32,memory,150123589428,object_store_memory,68624395468 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --redis-address=None --temp-dir=/tmp/ray --metrics-agent-port=59027 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --temp-dir=/tmp/ray --webui= RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:52383 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs -Dray.session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --log_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --resource_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --metrics-agent-port=59027 --metrics_export_port=53174 --object_store_memory=68624395468 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --labels= --head --num_prestart_python_workers=32 "--agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=53174 --dashboard-agent-port=59027 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --runtime-env-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --log-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-30_20-02-14_305409_1614546 --gcs-address=10.20.240.18:52383 --minimal"` due to (pid=1614755, name='raylet')
2024-07-02 07:05:25,465	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=2 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,CPU,2,memory,164658337997,object_store_memory,74853573427 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --redis-address=None --metrics-agent-port=46078 --runtime-env-agent-port=58341 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --temp-dir=/tmp/ray --webui= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:47294 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs -Dray.session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --resource_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --metrics-agent-port=46078 --metrics_export_port=61221 --runtime_env_agent_port=58341 --object_store_memory=74853573427 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --labels= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 --head --num_prestart_python_workers=2 "--dashboard_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=61221 --dashboard-agent-port=46078 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-28_07-48-43_813905_1894806 --gcs-address=10.20.240.18:47294 --minimal" "--runtime_env_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=10.20.240.18 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --runtime-env-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --temp-dir=/tmp/ray"` due to (pid=1894993, name='raylet')
2024-07-02 07:05:25,470	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/log_monitor.py --logs-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --gcs-address=10.20.240.18:52383 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5` due to (pid=1614784, name='python3')
2024-07-02 07:05:25,470	VINFO scripts.py:1122 -- Attempted to stop `/home/s2240084/conFEDential/venv/bin/python -u /home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/_private/log_monitor.py --session-dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969 --logs-dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969/logs --gcs-address=10.20.240.18:6379 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5`, but process was already dead.
2024-07-02 07:05:25,470	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/log_monitor.py --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --logs-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --gcs-address=10.20.240.18:47294 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5` due to (pid=1895026, name='python3')
2024-07-02 07:05:25,480	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=32 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,accelerator_type:G,1,CPU,32,memory,150123589428,object_store_memory,68624395468 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --redis-address=None --temp-dir=/tmp/ray --metrics-agent-port=59027 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --temp-dir=/tmp/ray --webui= RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:52383 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs -Dray.session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --log_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --resource_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --metrics-agent-port=59027 --metrics_export_port=53174 --object_store_memory=68624395468 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:52383 --session-name=session_2024-06-30_20-02-14_305409_1614546 --labels= --head --num_prestart_python_workers=32 "--agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=53174 --dashboard-agent-port=59027 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --runtime-env-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --log-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-30_20-02-14_305409_1614546 --gcs-address=10.20.240.18:52383 --minimal"` due to (pid=1614755, name='raylet')
2024-07-02 07:05:25,480	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=53174 --dashboard-agent-port=59027 --listen-port=52365 --node-manager-port=45039 --object-store-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --runtime-env-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/runtime_resources --log-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-30_20-02-14_305409_1614546 --gcs-address=10.20.240.18:52383 --minimal --agent-id 424238335` due to (pid=1614816, name='python3')
2024-07-02 07:05:25,481	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=2 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,CPU,2,memory,164658337997,object_store_memory,74853573427 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --redis-address=None --metrics-agent-port=46078 --runtime-env-agent-port=58341 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --temp-dir=/tmp/ray --webui= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:47294 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs -Dray.session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --resource_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --metrics-agent-port=46078 --metrics_export_port=61221 --runtime_env_agent_port=58341 --object_store_memory=74853573427 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --labels= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 --head --num_prestart_python_workers=2 "--dashboard_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=61221 --dashboard-agent-port=46078 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-28_07-48-43_813905_1894806 --gcs-address=10.20.240.18:47294 --minimal" "--runtime_env_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=10.20.240.18 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --runtime-env-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --temp-dir=/tmp/ray"` due to (pid=1894993, name='raylet')
2024-07-02 07:05:25,481	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=61221 --dashboard-agent-port=46078 --listen-port=52365 --node-manager-port=43953 --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-28_07-48-43_813905_1894806 --gcs-address=10.20.240.18:47294 --minimal --agent-id 424238335` due to (pid=1895073, name='python3')
2024-07-02 07:05:25,486	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/dashboard.py --host=127.0.0.1 --port=8265 --port-retries=50 --temp-dir=/tmp/ray --log-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --session-dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:52383 --node-ip-address=10.20.240.18 --minimal` due to (pid=1614716, name='python3')
2024-07-02 07:05:25,486	VINFO scripts.py:1114 -- Send termination request to `/home/s2240084/conFEDential/venv/bin/python /home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/dashboard/dashboard.py --host=127.0.0.1 --port=8265 --port-retries=0 --temp-dir=/local/ray --log-dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969/logs --session-dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:6379 --node-ip-address=10.20.240.18 --minimal` (via SIGTERM)
2024-07-02 07:05:25,486	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/dashboard.py --host=127.0.0.1 --port=8265 --port-retries=50 --temp-dir=/tmp/ray --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=10.20.240.18:47294 --node-ip-address=10.20.240.18 --minimal` due to (pid=1894944, name='python3')
2024-07-02 07:05:25,492	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --store_socket_name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --object_manager_port=0 --min_worker_port=0 --max_worker_port=0 --node_manager_port=0 --node_ip_address=10.20.240.18 --maximum_startup_concurrency=2 --static_resource_list=node:10.20.240.18,1.0,node:__internal_head__,1.0,CPU,2,memory,164658337997,object_store_memory,74853573427 "--python_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/default_worker.py --node-ip-address=10.20.240.18 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --redis-address=None --metrics-agent-port=46078 --runtime-env-agent-port=58341 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --temp-dir=/tmp/ray --webui= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER" "--java_worker_command=/local/s2085232/venv/bin/python3 /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/workers/setup_worker.py -Dray.address=10.20.240.18:47294 -Dray.raylet.node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER -Dray.object-store.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store -Dray.raylet.socket-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet -Dray.redis.password= -Dray.node-ip=10.20.240.18 -Dray.home=/local/s2085232/venv/lib/python3.10/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs -Dray.session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker" --cpp_worker_command= --native_library_path=/local/s2085232/venv/lib/python3.10/site-packages/ray/cpp/lib --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --resource_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --metrics-agent-port=46078 --metrics_export_port=61221 --runtime_env_agent_port=58341 --object_store_memory=74853573427 --plasma_directory=/dev/shm --ray-debugger-external=0 --gcs-address=10.20.240.18:47294 --session-name=session_2024-06-28_07-48-43_813905_1894806 --labels= --cluster-id=cb02afadfbeb3ec44ae1b4a34781c1d634401f9c2b288b14d8d746c0 --head --num_prestart_python_workers=2 "--dashboard_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/dashboard/agent.py --node-ip-address=10.20.240.18 --metrics-export-port=61221 --dashboard-agent-port=46078 --listen-port=52365 --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/plasma_store --raylet-name=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/sockets/raylet --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --session-name=session_2024-06-28_07-48-43_813905_1894806 --gcs-address=10.20.240.18:47294 --minimal" "--runtime_env_agent_command=/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=10.20.240.18 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --runtime-env-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --temp-dir=/tmp/ray"` due to (pid=1894993, name='raylet')
2024-07-02 07:05:25,492	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/bin/python3 -u /local/s2085232/venv/lib/python3.10/site-packages/ray/_private/runtime_env/agent/main.py --node-ip-address=10.20.240.18 --runtime-env-agent-port=58341 --gcs-address=10.20.240.18:47294 --runtime-env-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/runtime_resources --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --log-dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --temp-dir=/tmp/ray` due to (pid=1895075, name='python3')
2024-07-02 07:05:25,524	INFO scripts.py:1144 -- 1/4 stopped.2024-07-02 07:05:25,524	INFO scripts.py:1144 -- 2/4 stopped.2024-07-02 07:05:25,777	INFO scripts.py:1144 -- 3/4 stopped.2024-07-02 07:05:26,111	INFO scripts.py:1144 -- 4/4 stopped.2024-07-02 07:05:26,220	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/session_2024-06-30_20-02-14_305409_1614546/logs --config_list=eyJvYmplY3Rfc3BpbGxpbmdfY29uZmlnIjogIntcInR5cGVcIjogXCJmaWxlc3lzdGVtXCIsIFwicGFyYW1zXCI6IHtcImRpcmVjdG9yeV9wYXRoXCI6IFwiL3RtcC9yYXkvc2Vzc2lvbl8yMDI0LTA2LTMwXzIwLTAyLTE0XzMwNTQwOV8xNjE0NTQ2XCJ9fSIsICJpc19leHRlcm5hbF9zdG9yYWdlX3R5cGVfZnMiOiB0cnVlfQ== --gcs_server_port=52383 --metrics-agent-port=59027 --node-ip-address=10.20.240.18 --session-name=session_2024-06-30_20-02-14_305409_1614546` due to (pid=1614631, name='gcs_server')
2024-07-02 07:05:26,220	VINFO scripts.py:1114 -- Send termination request to `/home/s2240084/conFEDential/venv/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/local/ray/session_2024-07-01_01-55-19_924071_1695969/logs --config_list=eyJvYmplY3Rfc3BpbGxpbmdfY29uZmlnIjogIntcInR5cGVcIjogXCJmaWxlc3lzdGVtXCIsIFwicGFyYW1zXCI6IHtcImRpcmVjdG9yeV9wYXRoXCI6IFwiL2xvY2FsL3JheS9zZXNzaW9uXzIwMjQtMDctMDFfMDEtNTUtMTlfOTI0MDcxXzE2OTU5NjlcIn19IiwgImlzX2V4dGVybmFsX3N0b3JhZ2VfdHlwZV9mcyI6IHRydWV9 --gcs_server_port=6379 --metrics-agent-port=48709 --node-ip-address=10.20.240.18 --session-name=session_2024-07-01_01-55-19_924071_1695969` (via SIGTERM)
2024-07-02 07:05:26,221	ERR scripts.py:1127 -- Could not terminate `/local/s2085232/venv/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/session_2024-06-28_07-48-43_813905_1894806/logs --config_list=eyJvYmplY3Rfc3BpbGxpbmdfY29uZmlnIjogIntcInR5cGVcIjogXCJmaWxlc3lzdGVtXCIsIFwicGFyYW1zXCI6IHtcImRpcmVjdG9yeV9wYXRoXCI6IFwiL3RtcC9yYXkvc2Vzc2lvbl8yMDI0LTA2LTI4XzA3LTQ4LTQzXzgxMzkwNV8xODk0ODA2XCJ9fSIsICJpc19leHRlcm5hbF9zdG9yYWdlX3R5cGVfZnMiOiB0cnVlfQ== --gcs_server_port=47294 --metrics-agent-port=46078 --node-ip-address=10.20.240.18 --session-name=session_2024-06-28_07-48-43_813905_1894806` due to (pid=1894828, name='gcs_server')
2024-07-02 07:05:26,635	INFO scripts.py:1144 -- 1/1 stopped.2024-07-02 07:05:26,635	SUCC scripts.py:1189 -- Stopped all 6 Ray processes.
